---
title: "2.6: Long Run Industry Equilibrium - Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

# Overview

- *Tuesday, March 31, 2020*
- *Quarantine Lecture 3*

We wrap up Unit 2 on Producers today, by bringing our *optimization* model of how firms maximize profits into the long run, when firms can enter or exit depending on profitability. We also now need to talk about the fact that our firm is not the *only* profit-maximizing firm in the market, so we derive an **equilibrium** model of the industry in the long run.

Famously, we see that in *competitive* industries, economic profits get driven to zero in the long run, as firms enter or exit any time there are profits or losses.

We also talk about the hard to understand, but extremely important, idea of economic rents.

We will begin Unit 3, our interlude on Market Equilibrium, next class. As we have finished Unit 2 today, Exam 2 will be released next week. I will discuss it more on Thursday.

# Class Livestream/Lecture Videos

<iframe width="560" height="315" src="https://www.youtube.com/embed/MVfDaT5n3Fg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/Gv8NSUicWvE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/sVFWxkjHz8s" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/sniju3TzNks" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/bPW1wwGUCoQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/iSFsXEYdEho" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# Slides

- [<i class="fas fa-external-link-square-alt"></i> Lecture Slides](/slides/2.6-slides.html)

# Practice

We didn't have a formal practice, but I put up [<i class="fas fa-file-pdf"></i> `answers`](/practice/2.6-practice-answers.pdf) to the problem at the end of the slides that I skipped for time.

# Assignments: HW 4 and Exam 2

[Homework 3](/assignment/03-problem-set) answers will be posted on that page shortly.

[Homework 4](/assignment/04-problem-set) is due 11:59PM Sunday April 5 by email. **Please attach your document as a PDF!**

Exam 2 will be made available next week. I will discuss it more on Thursday.

# Midterm Course Grades, and Exam 1 Corrections

As per the Registrar, all faculty were required to issue midterm course grades on Monday March 30. I *estimated* your grade based on the assignments we have completed so far - Exam 1 (20%) and your current homework average (20%)^[This is the average of HW 1 and HW 2. I have not yet graded HW 3.] out of a total of 50%, not 100%. You can again estimate your final course grade (out of 100%) on the [<i class="fas fa-calculator"></i> `Grade Calculator`](https://ryansafner.shinyapps.io/306_grade_calculator/) at the top of the [Assignments page](/assignments). 

Thank you to those of you who completed Exam 1 corrections so far, those were included in your midterm grade, and I will be emailing your PDFs back to you with my markup and grades.

I decided to add a curve of +20 points to all Exam 1 grades. This was reflected in the midterm grades I posted. As you all continue to turn in Exam 1 corrections, I am averaging your raw scores and corrected scores as I announced I would, and then adding 20 to give you the ultimate grade for Exam 1. This will be posted in Blackboard. Please let me know if you have any concerns or do not understand my process.

# Appendix

## Cut for time: External Economies

I was going to talk about **external economies**, which are cost externalities within an entire industry, but we will be skipping this for time. I put my slides here if you want to know more.

The idea is firms entering/exiting a profitable/unprofitable industry over the long run certainly shift the industry supply curve and change the market equilibrium. But in a lot of industries as more firms enter and produce and compete with one another, that might raise costs for *all firms* (increasing cost industry/external diseconomies) or lower costs for *all firms* (decreasing cost industry/external economies). These effects may create either an upward sloping, flat, or downward sloping industry supply curve over the long run.

- [<i class="fas fa-external-link-square-alt"></i> External Economies](/slides/external-economies.html)

## Cut for time: Factor Markets

I was going to do a day on **factor markets** (markets for factors of production, like labor and capital, and where their prices $w$ and $r$ actually come from), but we will be skipping this for time. I did cover it fully in my Industrial Organization class [if you are interested](https://ios20.classes.ryansafner.com/class/1.8-class/).


