---
title: "4.1: Monopoly - Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

# Overview

- *Tuesday, April 14, 2020*
- *Quarantine Lecture 7*

Today we begin our look at monopoly.

# Slides

- [<i class="fas fa-external-link-square-alt"></i> Lecture Slides](/slides/4.1-slides.html)

# Practice Problems

Today we will be working on [practice problems](/practice/4.1-practice). Answers will be posted later.

# Exam 2 Corrections

I am still grading your Exam 2, I hope to finish for next class. Sorry it's been a crazy semester!

# Problem Set 5 Due Mon/Tues Dec 2/3

[Homework 5](/assignment/05-problem-set) on classes 3.1-3.3 is **due by email** (**as a PDF**) at **11:59PM Sunday April 19**.

This will be your **final graded homework** of the semester. A reminder, the homework grade (20% of course grade) is the *average* of your homework grades. Again, see the [grade calculator](https://ryansafner.shinyapps.io/306_grade_calculator/) or the [syllabus](/syllabus) to estimate how this impacts your overall grade.

I will give a "homework" (with answers, of course) on Unit 4 which we are currently covering, so that you can practice for the Final exam, but I will not collect or grade it.

# Appendix

## Monopolists Only Produce Where Demand is Elastic: Proof

Let's first show the relationship between $MR(q)$ and price elasticity of demand, $\epsilon_D$. 

$$\begin{align*}
MR(q) &= p+\bigg(\frac{\Delta p}{\Delta q}\bigg)q && \text{Definition of } MR(q)\\
\frac{MR(q)}{p} &= \frac{p}{p}+\bigg(\frac{\Delta p}{\Delta q}\bigg) \frac{q}{p} && \text{Dividing both sides by } p\\
\frac{MR(q)}{p} &= 1+\underbrace{\bigg(\frac{\Delta p}{\Delta q}\times \frac{q}{p} \bigg)}_{\frac{1}{\epsilon}}  && \text{Simplifying}\\
\frac{MR(q)}{p} &= 1+\frac{1}{\epsilon_D} && \text{Recognize price elasticity } \epsilon_D=\frac{\Delta q}{\Delta p} \times \frac{p}{q}\\
MR(q) &= p\bigg(1+\frac{1}{\epsilon_D}\bigg) && \text{Multiplying both sides by }p\\
\end{align*}$$

Remember, we've simplified $\epsilon_D = \frac{1}{slope} \times \frac{p}{q}$, where $\frac{1}{slope} = \frac{\Delta q}{\Delta p}$ because on a demand curve, $slope = \frac{\Delta p}{\Delta q}$.

Now that we have this alternate expression for $MR(q)$, lets assume $MC(q) \geq 0$ and set them equal to one another to maximize profits:

$$\begin{align*}
MR(q) &= MC(q)\\
p(1+\frac{1}{\epsilon_D}) & = MC(q)\\
p(1-\frac{1}{|\epsilon_D|}) & = MC(q)\\
\end{align*}$$

I rearrange the last line only to remind us that $\epsilon_D$ is always negative! 

Now note the following:

- If $|\epsilon_D| < 1$, then $MR(q)$ is *negative*. Since $MC(q)$ is assumed to be positive, it cannot equal a negative $MR(q)$, hence this is not profit-maximizing.
- If $|\epsilon_D| = 1$, then $MR(q)$ is 0. Only if $MC(q)$ is also 0 is this profit-maximizing.
- If $|\epsilon_D| > 1$, then $MR(q)$ is *positive*. It can equal a positive $MC(q)$ to be profit-maximizing.

Hence, a monopolist will *never* produce in the inelastic region of the demand curve (where $MR(q)<0)$, and will *only* produce at the unit elastic part of the demand curve (where $MR(q)=0)$ if $MC(q)=0$. Thus, it generally produces in the elastic region where $MR(q)>0$. 

See the graphs on [slide 22](/slides/4.1-slides.html#22).

## Derivation of the Lerner Index

Marginal revenue is strongly related to the **price elasticity of demand**, which is $E_{D}=\frac{\Delta q}{\Delta p} \times \frac{p}{q}$^[I sometimes simplify it as $E_{D}=\frac{1}{slope} \times \frac{p}{q}$, where "slope" is the slope of the inverse demand curve (graph), since the slope is $\frac{\Delta p}{\Delta q} = \frac{rise}{run}$.]

We derived marginal revenue (in the slides) as:
$$MR(q)=p+\frac{\Delta p}{\Delta q}q$$

Firms will always maximize profits where: 

$$\begin{align*}
MR(q)&=MC(q) && \text{Profit-max output}\\
p+\bigg(\frac{\Delta p}{\Delta q}\bigg)q&=MC(q) && \text{Definition of } MR(q)\\
p+\bigg(\frac{\Delta p}{\Delta q}\bigg) q \times \frac{p}{p}&=MC(q) && \text{Multiplying the left by } \frac{p}{p} \text{ (i.e. 1)}\\
p+\underbrace{\bigg(\frac{\Delta p}{\Delta q}\times \frac{q}{p} \bigg)}_{\frac{1}{\epsilon}} \times p &=MC(q) && \text{Rearranging the left}\\
p+\frac{1}{\epsilon} \times p &=MC(q) && \text{Recognize price elasticity } \epsilon=\frac{\Delta q}{\Delta p} \times \frac{p}{q}\\
p &=MC(q) - \frac{1}{\epsilon} p && \text{Subtract  }\frac{1}{\epsilon}p \text{ from both sides}\\
p-MC(q) &= -\frac{1}{\epsilon} p && \text{Subtract  }MC(q) \text{ from both sides}\\
\frac{p-MC(q)}{p} &= -\frac{1}{\epsilon} && \text{Divide both sides by  }p\\
		\end{align*}$$

The left side gives us the fraction of price that is markup $\left(\frac{p-MC(q)}{p}\right)$, and the right side shows this is inversely related to price elasticity of demand.