---
title: "4.2: Consequences and Sources of Market Power - Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

# Overview

- *Thursday, April 16, 2020*
- *Quarantine Lecture 8*

Today we continue our look at market power, by looking at the social consequences of market power: deadweight loss, allocative inefficiency, and rent-seeking; as well as the primary causes: control over a key resource, barriers to entry, and economies of scale.

# Class Livestream/Videos

<iframe width="560" height="315" src="https://www.youtube.com/embed/4JPueNro_-A" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/MdE-YokKrpI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/e0e8-w_sn_8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/u1OtR7V23O0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/ApCJP1d6hp4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# Slides

- [<i class="fas fa-external-link-square-alt"></i> Lecture Slides](/slides/4.2-slides.html)

# Problem Set 5 Due 11:59PM Sunday April 19

[Homework 5](/assignment/05-problem-set) on classes 3.1-3.3 is **due by email** (**as a PDF**) at **11:59PM Sunday April 19**.

This will be your **final graded homework** of the semester. A reminder, the homework grade (20% of course grade) is the *average* of your homework grades. Again, see the [grade calculator](https://ryansafner.shinyapps.io/306_grade_calculator/) or the [syllabus](/syllabus) to estimate how this impacts your overall grade.

I will give a "homework" (with answers, of course) on Unit 4 which we are currently covering, so that you can practice for the Final exam, but I will not collect or grade it.