---
title: "Exam 2 Information"
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(pander)
source(file.path(here::here(), "lib", "graphics.R"))
```

**Exam 2 will be available 8:00 AM _Tuesday, April 7 through 10:00 PM Sunday April 12_ on Blackboard**^[Go to our class Blackboard page, on the blue navigation bar on the left, click *Assignments*, you will find Exam 2.]

# Exam Instructions (IMPORTANT, PLEASE READ)

This test will be available on Blackboard as a *timed* assignment. You will have **2 hours once you open the test on Blackboard**. You will *not* need the whole time, I have given you some extra to accomodate the difficulties of taking an exam at home. **Please pick a time to take it where you know you will have 2 hours**. You may close the exam page and come back to it, but *the timer will continue to run* once the exam is first opened.

This is an **open note, open book** exam, but **do not use the internet beyond our class website, or contact each other**^[Google won't help you here. Everything you need should be in your notes, homeworks, or slides anyway!] I will interpret substantially-similarly-written answers, or obviously-googled answers as cheating or plagiarism, respectively. Answers should be *in your own words*, I will deduct points for blatant copy-pastes off my slides (those are *my* words!).

There is a **practice exam** on Blackboard that **I would like you to take**, so you can see what the exam will look like, and to make sure you can access and complete it. **Please try this before Sunday April 5 and email me if you ran into any issues.** This is to help make sure this format works for everyone.

# Concepts Study Guide

- [<i class="fas fa-file-pdf"></i> `Download PDF`](/examprep/exam_w_study_guide.pdf)

# "Practice" Exam

- [<i class="fas fa-file-pdf"></i> `Download Old Exam 2`](/examprep/Exam2.pdf)^[Note: Question 1 pertains to a topic that we skipped due to time. You would not be responsible for that material on our exam.]

Above, you have a previous semester's exam 2. Use it to get a sense of what questions are asked, the format, and how many. Questions draw from topics in Unit 2, and note that **just because topics or questions were not in the practice exam does NOT mean they may not show up on your exam.**^[I hope that this is obvious. I write this to ensure there is no misunderstanding.] Aside from minor extensions, no mathematical problem on any exam should be something you have not seen in some form before. 

I will post the **answer key** on the **evening of Sunday April 5**. I am happy to discuss other individual answers and strategies during Office Hours.

# My Advice

Make sure you do all of the homework problems and learn from the answer keys to the homeworks, as well as the in-class practice problems. All of the math problems are largely in the style of the homework questions. While some of the questions should be novel applications, conceptual questions on homeworks will get you in the right headspace to think about answering a question on an exam.^[The point of exams is to *apply* what you've learned, not to literally regurgitate it! Or, at least, it should be.]